# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 10
cache:
  - npm
  - pip

jobs:
  include:
    - stage: Publish_dashboard
      name: Update travis build dashboard
      if: branch = master

      script: skip

      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: public
          github_token: $GITHUB_TOKEN


stages:
  - Unit_test
  - Test
  - Build
  - Deploy
  - Integration_to_other_repo
  - Publish_dashboard
  - Merge

import:
  - credentials.yml
