# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 10
cache:
  - npm
  - pip

jobs:
  include:
    - stage: Publish_dashboard
      name: Update travis build dashboard

      script:
        - scripts/publish.sh

      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: gh-pages
          github_token: $GITHUB_TOKEN
          on:
            branch: master

      if: branch = master


stages:
  - Unit_test
  - Test
  - Build
  - Deploy
  - Integration_to_other_repo
  - Publish_dashboard
  - Merge

import:
  - credentials.yml
